### ISSUE TITLE
Proposal for a create-rs-app cli for a simple npx command to clone a rocket-science app

### ISSUE THREAD

**Issue by ahoward2** [SketchLagoon/rocket-science#5]
We can publish a repo like this https://github.com/ahoward2/create-rs-app as an npm package.

npx create-rs-app

Then inquirer asks for an app name.

We can also add an option to clone a js, strict ts version, etc if we have different branches of the rocket-science repo.

**Comment by SketchLagoon** [comment]
Great idea!!!

**Comment by ahoward2** [comment]
> Great idea!!! Let's call the setup phase "liftoff" lol

So many rocket science terms we can use for things 😂
