### ISSUE TITLE
Strict TS Branch

### ISSUE THREAD

**Issue by SketchLagoon** [SketchLagoon/rocket-science#8]
We are currently oriented towards a TS leaning repository, but we should fully immerse ourselves in it so that we can provide an option in the "create-rs-app" CLI to generate a strict ts version.

**Comment by ahoward2** [comment]
Running npx create-rs-app now has added option to clone the main (loose ts) branch by default, and strict-typescript branch as a secondary option. We'll just have to keep the two branches in parity.
