### ISSUE TITLE
ES6+ Branch

### ISSUE THREAD

**Issue by SketchLagoon** [SketchLagoon/rocket-science#9]
We are currently oriented towards a TS leaning repository, but we should also create an ES6+ version so that we can provide an option in the "create-rs-app" CLI to generate an ES6+ project for those that would prefer it to TS

**Comment by ahoward2** [comment]
npx create-rs-app now has an option to clone the javascript branch of rocket-science. we should formalize some method of keeping these branches up to date with one another
